# Joining and cleaning data for UCLA EDA Final Project

### Importing Libraries and Data

In [36]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


# Read in the data
housing = pd.read_csv('data/housing.csv')
schools = pd.read_csv('data/schools.csv')

In [37]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   neighborhood  683 non-null    object 
 1   beds          683 non-null    int64  
 2   baths         683 non-null    float64
 3   sqft          681 non-null    float64
 4   lotsize       663 non-null    float64
 5   year          683 non-null    int64  
 6   type          683 non-null    object 
 7   levels        683 non-null    object 
 8   cooling       676 non-null    object 
 9   heating       676 non-null    object 
 10  fireplace     677 non-null    object 
 11  elementary    683 non-null    object 
 12  middle        683 non-null    object 
 13  high          683 non-null    object 
 14  soldprice     683 non-null    int64  
dtypes: float64(3), int64(3), object(9)
memory usage: 80.2+ KB


In [38]:
schools.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   school  52 non-null     object
 1   size    52 non-null     int64 
 2   rating  52 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 1.3+ KB


### Data Joining

In [39]:
# Merge the data
# Use list to join each school type to the housing data
s_types = ["Elementary", "Middle", "High"]

# Create temporary dataframes for each school type and merge with housing dataframe
# Add size and rating columns to the housing dataframe for each school type
for s_type in s_types:

    size_col_name = (s_type + "_size").lower()
    rating_col_name = (s_type + "_rating").lower()

    tdf = schools[schools['school'].str.contains(s_type)]
    housing = housing.merge(tdf, left_on=s_type.lower(), right_on='school', how='left')

    housing = housing.rename(columns={'size': size_col_name, 'rating': rating_col_name})

# Remove the redundant school columns
housing.drop(columns=['school_x', 'school_y', 'school'], inplace=True)

In [40]:
cols = ['neighborhood', 'beds', 'baths', 'sqft', 'lotsize', 'year', 'type',
       'levels', 'cooling', 'heating', 'fireplace', 'soldprice', 'elementary',
       'elementary_size','elementary_rating', 'middle','middle_size','middle_rating',
       'high','high_size', 'high_rating']

housing = housing[cols]

In [41]:
housing.columns

Index(['neighborhood', 'beds', 'baths', 'sqft', 'lotsize', 'year', 'type',
       'levels', 'cooling', 'heating', 'fireplace', 'soldprice', 'elementary',
       'elementary_size', 'elementary_rating', 'middle', 'middle_size',
       'middle_rating', 'high', 'high_size', 'high_rating'],
      dtype='object')

In [42]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 683 entries, 0 to 682
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   neighborhood       683 non-null    object 
 1   beds               683 non-null    int64  
 2   baths              683 non-null    float64
 3   sqft               681 non-null    float64
 4   lotsize            663 non-null    float64
 5   year               683 non-null    int64  
 6   type               683 non-null    object 
 7   levels             683 non-null    object 
 8   cooling            676 non-null    object 
 9   heating            676 non-null    object 
 10  fireplace          677 non-null    object 
 11  soldprice          683 non-null    int64  
 12  elementary         683 non-null    object 
 13  elementary_size    683 non-null    int64  
 14  elementary_rating  683 non-null    int64  
 15  middle             683 non-null    object 
 16  middle_size        683 non

In [43]:
housing.describe()

beds       baths         sqft     lotsize         year  \
count  683.000000  683.000000   681.000000  663.000000   683.000000   
mean     4.937042    2.001464  2127.562408    0.288869  1977.461201   
std     38.121012    1.392269  1069.311206    0.184496    30.280016   
min      1.000000    1.000000   536.000000    0.070000  1495.000000   
25%      3.000000    1.000000  1349.000000    0.160000  1961.000000   
50%      4.000000    1.500000  1955.000000    0.240000  1978.000000   
75%      4.000000    2.500000  2676.000000    0.360000  1997.000000   
max    999.000000   25.000000  5265.000000    1.300000  2111.000000   

          soldprice  elementary_size  elementary_rating  middle_size  \
count  6.830000e+02       683.000000         683.000000   683.000000   
mean   1.244857e+06       742.825769           5.746706   693.265007   
std    3.761917e+05       102.282215           2.404535   120.233272   
min    6.640000e+02       600.000000           1.000000   500.000000   
25%    9.745000e+05       700.000000           4.000000   600.000000   
50%    1.267000e+06       750.000000           6.000000   700.000000   
75%    1.548000e+06       800.000000           8.000000   800.000000   
max    2.393000e+06       900.000000          10.000000   900.000000   

       middle_rating    high_size  high_rating  
count     683.000000   683.000000   683.000000  
mean        6.178624   967.423133     5.926794  
std         1.948083   153.084918     2.920837  
min         2.000000   750.000000     1.000000  
25%         5.000000   850.000000     4.000000  
50%         7.000000  1000.000000     6.000000  
75%         8.000000  1100.000000     8.000000  
max         9.000000  1250.000000    10.000000

### Data Cleaning

The goal of data cleaning is to handle missing values, remove outliers, and handle any other data issues that may arise. The data cleaning process is iterative, so it is important to keep track of the changes made to the data.

In [44]:
# Change some columns to categorical.
housing['cooling'] = pd.Categorical(housing['cooling'], categories=['Yes', 'No'], ordered=True)
housing['heating'] = pd.Categorical(housing['heating'], categories=['Yes', 'No'], ordered=True)
housing['fireplace'] = pd.Categorical(housing['fireplace'], categories=['Yes', 'No'], ordered=True)
housing['type'] = pd.Categorical(housing['type'], ordered=True)

In [45]:
nbhs = housing.groupby('neighborhood')['soldprice'].mean().sort_values(ascending=False).index.to_list()

housing['neighborhood'] = pd.Categorical(housing['neighborhood'], categories=nbhs, ordered=True)

In [46]:
housing.to_csv('data/joined.csv', index=False)

#### Missing Values

For the first iteration of analysis, we will drop all rows with missing values in any column. In the future, we may want to impute missing values where possible and appropriate.

In [47]:
housing.dropna(inplace=True)
print(housing.shape)

(645, 21)


In [48]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 645 entries, 0 to 682
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   neighborhood       645 non-null    category
 1   beds               645 non-null    int64   
 2   baths              645 non-null    float64 
 3   sqft               645 non-null    float64 
 4   lotsize            645 non-null    float64 
 5   year               645 non-null    int64   
 6   type               645 non-null    category
 7   levels             645 non-null    object  
 8   cooling            645 non-null    category
 9   heating            645 non-null    category
 10  fireplace          645 non-null    category
 11  soldprice          645 non-null    int64   
 12  elementary         645 non-null    object  
 13  elementary_size    645 non-null    int64   
 14  elementary_rating  645 non-null    int64   
 15  middle             645 non-null    object  
 16  middle_s

In [49]:
housing.describe().style.text_gradient(axis=0)

#### Outliers

The summary statistics show outliers in our data. Below is a list of the columns with outliers:

- `baths` : 1 outlier; max value of 25 (likely 2.5)
- `year` : 2 outliers; min value of 1495, max value of 2111 (likely 1945, 2011)
- `soldprice` : 1 outlier; min value of $664 (likely $664,000)

For the first analysis, we will drop all rows with outliers in any column. In the future, we may want to consider imputing the outliers.

In [50]:
msk_b = housing['baths'] < 25
msk_y1 = housing['year'] > 1495
msk_y2 = housing['year'] < 2111
msk_sp = housing['soldprice'] > 664

select = pd.concat([msk_b, msk_y1, msk_y2, msk_sp], axis=1).all(axis=1)

#select = select.all()
print("Outlier Rows")
housing[~select].style.text_gradient(axis=0, subset=['baths', 'year', 'soldprice'])

Outlier Rows


In [51]:
housing = housing[select].reset_index(drop=True)

In [52]:
housing.describe().style.text_gradient(axis=0)

In [53]:
housing.columns

Index(['neighborhood', 'beds', 'baths', 'sqft', 'lotsize', 'year', 'type',
       'levels', 'cooling', 'heating', 'fireplace', 'soldprice', 'elementary',
       'elementary_size', 'elementary_rating', 'middle', 'middle_size',
       'middle_rating', 'high', 'high_size', 'high_rating'],
      dtype='object')

In [54]:
cols = ['beds', 'baths', 'sqft', 'lotsize', 'year', 'soldprice']

In [55]:
housing.loc[:,cols].reset_index(drop=True)

beds  baths    sqft  lotsize  year  soldprice
0       6    4.0  4233.0     0.88  1926    1289000
1       1    1.0   748.0     0.11  1985     499000
2       3    2.0  2001.0     0.23  1945     573000
3       6    3.5  4454.0     0.43  1938    1246000
4       4    3.0  2004.0     0.35  1959    1250000
..    ...    ...     ...      ...   ...        ...
636     3    1.0  1631.0     0.13  1966    1220000
637     3    1.0  1714.0     0.13  1967    1622000
638     4    2.5  2560.0     0.21  1977    1143000
639     4    2.5  2035.0     0.19  1949    1368000
640     6    5.0  4260.0     0.33  1977    1619000

[641 rows x 6 columns]

In [56]:
housing.to_csv('data/cleaned_01.csv', index=False)

In [57]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641 entries, 0 to 640
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   neighborhood       641 non-null    category
 1   beds               641 non-null    int64   
 2   baths              641 non-null    float64 
 3   sqft               641 non-null    float64 
 4   lotsize            641 non-null    float64 
 5   year               641 non-null    int64   
 6   type               641 non-null    category
 7   levels             641 non-null    object  
 8   cooling            641 non-null    category
 9   heating            641 non-null    category
 10  fireplace          641 non-null    category
 11  soldprice          641 non-null    int64   
 12  elementary         641 non-null    object  
 13  elementary_size    641 non-null    int64   
 14  elementary_rating  641 non-null    int64   
 15  middle             641 non-null    object  
 16  middle_s

### Imputation of Outliers and Mission Values

In [109]:
data = pd.read_csv('data/joined.csv')

In [110]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   neighborhood       683 non-null    object 
 1   beds               683 non-null    int64  
 2   baths              683 non-null    float64
 3   sqft               681 non-null    float64
 4   lotsize            663 non-null    float64
 5   year               683 non-null    int64  
 6   type               683 non-null    object 
 7   levels             683 non-null    object 
 8   cooling            676 non-null    object 
 9   heating            676 non-null    object 
 10  fireplace          677 non-null    object 
 11  soldprice          683 non-null    int64  
 12  elementary         683 non-null    object 
 13  elementary_size    683 non-null    int64  
 14  elementary_rating  683 non-null    int64  
 15  middle             683 non-null    object 
 16  middle_size        683 non

Below I will impute the missing values of the `lotsize` column by taking the average percent of square footage to lotsize, converting the sqft to acres and multiplying the percent by the acres.

In [111]:
data['pct_built'] = (data['sqft'] / (data['lotsize'] * 43560)) * 100
data['lotsize'].fillna((data['pct_built'].mean()) * (data['sqft'] / 43560), inplace=True)

In [112]:
data['lotsize'].describe()

count    683.000000
mean       0.305549
std        0.222838
min        0.070000
25%        0.160000
50%        0.250000
75%        0.370000
max        2.339692
Name: lotsize, dtype: float64

Below the outliers are replaced with the most likely values.

In [82]:
msk_b = data['baths'] < 25
msk_y1 = data['year'] > 1495
msk_y2 = data['year'] < 2111
msk_sp = data['soldprice'] > 664

data.loc[~msk_b, 'baths'] = 2.5
data.loc[~msk_y1, 'year'] = 1945
data.loc[~msk_y2, 'year'] = 2011
data.loc[~msk_sp, 'soldprice'] = 664000


In [83]:
select = pd.concat([msk_b, msk_y1, msk_y2, msk_sp], axis=1).all(axis=1)

#select = select.all()
print("Outlier Rows")
data[~select].style.text_gradient(axis=0, subset=['baths', 'year', 'soldprice'])

Outlier Rows


In [84]:
data.to_csv('data/cleaned_02.csv', index=False)